/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:0eb318c1-2de0-43ec-a7ac-c54878c13202",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_xnGhRPOvs",
    "aws_user_pools_web_client_id": "7thph84u6clivrrk788tb391d3",
    "oauth": {}
};


export default awsmobile;
