/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:253c0ceb-140e-489d-9ddb-204c5004cab4",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_o3GPvnFbu",
    "aws_user_pools_web_client_id": "5i8p9108dfed3u3uqufntdkdcd",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://z4caipoo7bflflr6vubphqheu4.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
