/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:1565afac-205d-4c30-b553-abb3eba5e833",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_cMJeDp9HF",
    "aws_user_pools_web_client_id": "3ki05snh7uehaqurs3fkta4201",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3kel5kvnuvehfifncb4qcs2kg4.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
